package ca.ubc.cs.reverb.indexer.installer;

public class ChromeVisitType {
    // From page_transition_types.h -- more details on the different transition types are available there.
    
    public final static int LINK = 0;
    public final static int TYPED = 1;
    public final static int AUTO_BOOKMARK = 2;
    public final static int AUTO_SUBFRAME = 3;
    public final static int MANUAL_SUBFRAME = 4;
    public final static int GENERATED = 5;
    public final static int START_PAGE = 6;
    public final static int FORM_SUBMIT = 7;
    public final static int RELOAD = 8;
    public final static int KEYWORD = 9;
    public final static int KEYWORD_GENERATED = 10;
    
    public final static int CORE_MASK = 0xFF;
    
    // Redirect flags.
    
    // Unfortunately, not all redirect chains start with a CHAIN_START transition.  
    // E.g. transition generated by a search from the Wikipedia home page.
    public final static int CHAIN_START =      0x10000000;
    public final static int CHAIN_END =        0x20000000;
    public final static int CLIENT_REDIRECT =  0x40000000;
    public final static int SERVER_REDIRECT =  0x80000000;
   
    // This is the mask in page_transition_types.h -- but we use 0xF0000000, which, empirically, captures 
    // more redirects (e.g. redirect from wikipedia.org to www.wikipedia.org).
    public final static int IS_REDIRECT_MASK = 0xC0000000;
    
    public final static int QUALIFIER_MASK =   0xFFFFFF00;

}
